# Remove local Python packaging artifacts (safe — regenerated by pip when needed).
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

$paths = @('build', 'dist', 'homy.egg-info', '.eggs')
foreach ($name in $paths) {
    if (Test-Path $name) {
        Remove-Item -Recurse -Force $name
        Write-Host "Removed $name"
    }
}

Get-ChildItem -Recurse -Directory -Filter '__pycache__' | Remove-Item -Recurse -Force
Write-Host 'Done.'
